### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by mvaljento** [lukeribchester/pact-intellij#60]
How do you actually get this plugin working on Mac? 

I tried setting the pact executable path in the latest WebStorm (tried "/opt/homebrew/bin/pact" and "/opt/homebrew/Cellar/pact/4.10.0", as well as pointing the language server path to the one that came with the plugin (pact-lsp-v0.0.1). The editor only shows the correct icon for the file, but that's it. No code completion, no syntax highlighting, no declarations found.. nada.

The file type seems to be correctly recognised. Plugin version 0.1.2, WebStorm 2024.1, Pact version 4.10.0 (installed via Homebrew).

Thanks!

**Comment by mvaljento** [comment]
@lukeribchester Hi Luke, thanks for the answer. Nothing works. I had a time to check the logs now and discovered this:

2024-04-25 08:42:56,541 [   8384]   INFO - #c.i.p.l.i.LspServerImpl - PactLspServerDescriptor@unitt-api(Initializing;0): Starting LSP server
2024-04-25 08:42:56,542 [   8385]   WARN - #c.i.p.l.i.LspServerImpl - PactLspServerDescriptor@unitt-api(Initializing;0): Failed to start LSP server
com.intellij.execution.ExecutionException: Pact Language Server (LSP) executable not found
	at io.kadena.pact.lsp.PactLspServerDescriptor.createCommandLine(PactLspServerDescriptor.kt:47)
	at com.intellij.platform.lsp.api.LspServerDescriptor.startServerProcess(LspServerDescriptor.kt:94)
	at com.intellij.platform.lsp.impl.connector.Lsp4jServerConnectorStdio.<init>(Lsp4jServerConnectorStdio.kt:17)
	at com.intellij.platform.lsp.impl.LspServerImpl.L(LspServerImpl.kt:318)
	at com.intellij.platform.lsp.impl.LspServerImpl.S(LspServerImpl.kt:298)
	at com.intellij.openapi.application.impl.RwLockHolder$executeOnPooledThread$1.run(RwLockHolder.kt:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-04-25 08:42:56,543 [   8386]   INFO - #c.i.p.l.i.LspServerImpl - PactLspServerDescriptor@unitt-api(Initializing;0): Stopping LSP server unexpectedly

I have set the following paths in the plugin settings:

Pact:
/opt/homebrew/Cellar/pact/4.10.0/bin/pact

Language server:
/Users/mikkoville/Library/Application Support/JetBrains/PhpStorm2024.1/plugins/Pact/language-server/macos/pact-lsp-v0.0.1

**Comment by mvaljento** [comment]
Okay, I think I got the LSP working by downloading the binary executable from the Github pact-lsp/releases and pointing the plugin to that. However, editing .pact files still does not seem to provide any language services, syntax colour highlighting or anything else.

![Screenshot 2024-04-25 at 9 42 19](https://github.com/lukeribchester/pact-intellij/assets/376610/b44658b7-899c-46dd-9dca-272009d87089)

**Comment by lukeribchester** [comment]
Indeed I see that it's a permission issue. It's not ideal but based on my testing you should be able to resolve this simply with `chmod +x /path/to/pact-lsp`.

I expect to release native language support over the weekend for approval by JetBrains on Monday or Tuesday, immediately after which I'll extend language server support to the Pact 5 LSP — including permission handling to resolve this.

See #35 

I'll close this now but thank you very much for raising this. 🙌🏻
